# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
cache: pip
services:
  - postgresql
python:
  - 2.7
  - 3.6
before_install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends libpq-dev
install: pip install -r requirements/dev.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/main/app.py"
  - export FLASK_DEBUG=1
  - psql -U postgres -c 'create database books;'
#  - psql -U postgres books < ./books.sql
  - pg_restore -d books ./books.tar -c -U postgres
script:
  - coverage run --source=main -m pytest --verbose
after_success:
  - coveralls